In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data/bike/2019/01001099999.csv')

In [3]:
display(df.columns)

Index(['STATION', 'DATE', 'LATITUDE', 'LONGITUDE', 'ELEVATION', 'NAME', 'TEMP',
       'TEMP_ATTRIBUTES', 'DEWP', 'DEWP_ATTRIBUTES', 'SLP', 'SLP_ATTRIBUTES',
       'STP', 'STP_ATTRIBUTES', 'VISIB', 'VISIB_ATTRIBUTES', 'WDSP',
       'WDSP_ATTRIBUTES', 'MXSPD', 'GUST', 'MAX', 'MAX_ATTRIBUTES', 'MIN',
       'MIN_ATTRIBUTES', 'PRCP', 'PRCP_ATTRIBUTES', 'SNDP', 'FRSHTT'],
      dtype='object')

In [4]:
ghcn = pd.read_csv('data/weather/weather2019.csv',
   usecols=["DATE","AWND","PRCP","SNOW","SNWD","TMAX","TMIN",
       "WT01","WT02","WT04","WT08"])

df2 = pd.read_csv('data/weather/weather2019.csv')

In [5]:
display(ghcn.columns)
display(df2.columns)

Index(['DATE', 'AWND', 'PRCP', 'SNOW', 'SNWD', 'TMAX', 'TMIN', 'WT01', 'WT02',
       'WT04', 'WT08'],
      dtype='object')

Index(['STATION', 'NAME', 'DATE', 'AWND', 'PGTM', 'PRCP', 'SNOW', 'SNWD',
       'TAVG', 'TMAX', 'TMIN', 'TSUN', 'WDF2', 'WDF5', 'WSF2', 'WSF5', 'WT01',
       'WT02', 'WT03', 'WT04', 'WT05', 'WT06', 'WT08'],
      dtype='object')

In [6]:
display(ghcn.head(5))
ghcn = ghcn.fillna(0)
ghcn['TMAX'] = round((ghcn['TMAX'] - 32)/1.8,1)
ghcn['TMIN'] = round((ghcn['TMIN'] - 32)/1.8,1)
col_dict = {'WT01':'fog', 'WT02':'heavy_fog', 'WT04':'sleet', 'WT08':'haze'}
ghcn.rename(columns=col_dict, inplace=True)
display(ghcn.head(5))

         DATE  AWND  PRCP  SNOW  SNWD  TMAX  TMIN  WT01  WT02  WT04  WT08
0  2019-01-01   NaN  0.06   0.0   0.0    58    39   1.0   NaN   NaN   NaN
1  2019-01-02   NaN  0.00   0.0   0.0    40    35   NaN   NaN   NaN   NaN
2  2019-01-03   NaN  0.00   0.0   0.0    44    37   NaN   NaN   NaN   NaN
3  2019-01-04   NaN  0.00   0.0   0.0    47    35   NaN   NaN   NaN   NaN
4  2019-01-05   NaN  0.50   0.0   0.0    47    41   1.0   NaN   NaN   NaN

         DATE  AWND  PRCP  SNOW  SNWD  TMAX  TMIN  fog  heavy_fog  sleet  haze
0  2019-01-01   0.0  0.06   0.0   0.0  14.4   3.9  1.0        0.0    0.0   0.0
1  2019-01-02   0.0  0.00   0.0   0.0   4.4   1.7  0.0        0.0    0.0   0.0
2  2019-01-03   0.0  0.00   0.0   0.0   6.7   2.8  0.0        0.0    0.0   0.0
3  2019-01-04   0.0  0.00   0.0   0.0   8.3   1.7  0.0        0.0    0.0   0.0
4  2019-01-05   0.0  0.50   0.0   0.0   8.3   5.0  1.0        0.0    0.0   0.0

In [7]:
int_col = ['SNOW', 'fog','heavy_fog','sleet','haze']
float_col = ['AWND','PRCP','SNWD','TMAX','TMIN']
date_col = ['DATE']

for col in float_col:
    print(f'col: {col}, min: {ghcn[col].min()}, max: {ghcn[col].max()}')
    
print(ghcn.dtypes)

col: AWND, min: 0.0, max: 12.75
col: PRCP, min: 0.0, max: 1.83
col: SNWD, min: 0.0, max: 3.9
col: TMAX, min: -10.0, max: 35.0
col: TMIN, min: -16.7, max: 27.8
DATE          object
AWND         float64
PRCP         float64
SNOW         float64
SNWD         float64
TMAX         float64
TMIN         float64
fog          float64
heavy_fog    float64
sleet        float64
haze         float64
dtype: object

In [8]:
def col_type_mod(df_mod):
    for col in int_col:
        df_mod[col] = pd.to_numeric(df_mod[col], downcast='integer')

    for col in float_col:
        df_mod[col] = pd.to_numeric(df_mod[col], downcast='float')
        
    for col in date_col:
        df_mod[col] = pd.to_datetime(df_mod[col])

    return df_mod

ghcn = col_type_mod(ghcn)
print(ghcn.dtypes)
display(ghcn.head(5))

DATE         datetime64[ns]
AWND                float32
PRCP                float32
SNOW                float64
SNWD                float32
TMAX                float32
TMIN                float32
fog                    int8
heavy_fog              int8
sleet                  int8
haze                   int8
dtype: object

        DATE  AWND  PRCP  SNOW  SNWD  TMAX  TMIN  fog  heavy_fog  sleet  haze
0 2019-01-01   0.0  0.06   0.0   0.0  14.4   3.9    1          0      0     0
1 2019-01-02   0.0  0.00   0.0   0.0   4.4   1.7    0          0      0     0
2 2019-01-03   0.0  0.00   0.0   0.0   6.7   2.8    0          0      0     0
3 2019-01-04   0.0  0.00   0.0   0.0   8.3   1.7    0          0      0     0
4 2019-01-05   0.0  0.50   0.0   0.0   8.3   5.0    1          0      0     0

In [9]:
ghcn['fsh'] = ghcn['fog'] | ghcn['heavy_fog'] | ghcn['sleet'] | ghcn['haze']
display(ghcn.head(10))

,DATE,AWND,PRCP,SNOW,SNWD,TMAX,TMIN,fog,heavy_fog,sleet,haze,fsh
0,2019-01-01,0.0,0.06,0.0,0.0,14.4,3.9,1,0,0,0,1
1,2019-01-02,0.0,0.00,0.0,0.0,4.4,1.7,0,0,0,0,0
2,2019-01-03,0.0,0.00,0.0,0.0,6.7,2.8,0,0,0,0,0
3,2019-01-04,0.0,0.00,0.0,0.0,8.3,1.7,0,0,0,0,0
4,2019-01-05,0.0,0.50,0.0,0.0,8.3,5.0,1,0,0,0,1
5,2019-01-06,0.0,0.00,0.0,0.0,9.4,-0.6,0,0,0,0,0
6,2019-01-07,0.0,0.00,0.0,0.0,1.1,-3.9,0,0,0,0,0
7,2019-01-08,0.0,0.17,0.0,0.0,7.2,1.1,1,0,0,0,1
8,2019-01-09,0.0,0.06,0.0,0.0,7.2,1.1,1,0,0,0,1
9,2019-01-10,0.0,0.00,0.0,0.0,1.1,-2.2,0,0,0,0,0

In [10]:
ghcn.to_csv('data/weather/2019_clean.csv')